export const cartActionTypes = {
    ADD_ITEM_TO_CART: 'ADD_ITEM_TO_CART',
    DELETE_ITEM_FROM_CART: 'DELETE_ITEM_FROM_CART',
    CHANGE_ITEM_AMOUNT: 'CHANGE_ITEM_AMOUNT',
    SET_CART_OPEN: 'SET_CART_OPEN',
    CLEAR_CART: 'CLEAR_CART'
}