export const reviewsActionsTypes = {
    SEND_REVIEW_REQUEST: 'SEND_REVIEW_REQUEST',
    SEND_REVIEW_SUCCESS: 'SEND_REVIEW_SUCCESS',
    SEND_REVIEW_FAILURE: 'SEND_REVIEW_FAILURE',
    SHOW_REVIEW_LOADER: "SHOW_REVIEW_LOADER",
    HIDE_REVIEW_LOADER: "HIDE_REVIEW_LOADER",
    SHOW_MODAL_WINDOW: "SHOW_MODAL_WINDOW",
    CLOSE_MODAL_WINDOW: "CLOSE_MODAL_WINDOW",
}