export const productsActionTypes = {
    FETCH_PRODUCTS: 'FETCH_PRODUCTS',
    FETCH_PRODUCTS_FAILURE: 'FETCH_PRODUCTS_FAILURE',
    FETCH_PRODUCTS_END: 'FETCH_PRODUCTS_END',
    SHOW_LOADER: "SHOW_LOADER",
    HIDE_LOADER: "HIDE_LOADER",
    ADD_REVIEW: 'ADD_REVIEW'
}