export const orderActionTypes = {
    FETCH_CITIES: 'FETCH_CITIES',
    FETCH_CITIES_ERROR: 'FETCH_CITIES_ERROR',
    FETCH_COUNTRIES: 'FETCH_COUNTRIES',
    FETCH_COUNTRIES_ERROR: 'FETCH_COUNTRIES_ERROR',
    SEND_ORDER: 'SEND_ORDER',
    SEND_ORDER_ERROR: 'SEND_ORDER_ERROR',
    CLEAR_ORDER_ERRORS: 'CLEAR_ORDER_ERRORS'
}