export const emailActionTypes = {
    SEND_EMAIL_MAIN_SUCCESS: 'SEND_EMAIL_MAIN_SUCCESS',
    SEND_EMAIL_MAIN_FAILURE: 'SEND_EMAIL_MAIN_FAILURE',
    SEND_EMAIL_FOOTER_SUCCESS: 'SEND_EMAIL_FOOTER_SUCCESS',
    SEND_EMAIL_FOOTER_FAILURE: 'SEND_EMAIL_FOOTER_FAILURE',
    SHOW_EMAIL_MAIN_LOADER: "SHOW_EMAIL_MAIN_LOADER",
    HIDE_EMAIL_MAIN_LOADER: "HIDE_EMAIL_MAIN_LOADER",
    SHOW_EMAIL_FOOTER_LOADER: "SHOW_EMAIL_FOOTER_LOADER",
    HIDE_EMAIL_FOOTER_LOADER: "HIDE_EMAIL_FOOTER_LOADER",
    BUTTON_MAIN_ENABLE: 'BUTTON_MAIN_ENABLE',
    BUTTON_MAIN_DISABLE: 'BUTTON_MAIN_DISABLE',
    BUTTON_FOOTER_ENABLE: 'BUTTON_FOOTER_ENABLE',
    BUTTON_FOOTER_DISABLE: 'BUTTON_FOOTER_DISABLE'
}